[tool.poetry]
name = "annorepo-client"
version = "0.1.1"
description = ""
authors = ["Bram Buitendijk <bram.buitendijk@di.huc.knaw.nl>"]
readme="README.md"
license="MIT"
homepage="https://github.com/brambg/annorepo-python-client"
repository="https://github.com/brambg/annorepo-python-client"
classifiers=[
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python"
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
