[tool.poetry]
name = "annorepo_client"
version = "0.1.0"
description = ""
authors = ["Bram Buitendijk <bram.buitendijk@di.huc.knaw.nl>"]
readme="README.md"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
